//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hercules.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountLeakOptions
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public Nullable<double> Radius { get; set; }
        public Nullable<int> RadiusUnits { get; set; }
        public Nullable<System.DateTime> TimeToRunAutoCorrelation { get; set; }
        public Nullable<int> LastRecordingID { get; set; }
        public Nullable<int> UseDefaultOptionIfNoPipe { get; set; }
    
        public virtual accounts accounts { get; set; }
        public virtual unitslookup unitslookup { get; set; }
    }
}
