//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hercules.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class accounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public accounts()
        {
            this.AccountLeakOptions = new HashSet<AccountLeakOptions>();
        }

        public int ID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> DatagateID { get; set; }
        public Nullable<int> Parent { get; set; }
        public Nullable<int> AccountType { get; set; }
        public string AccountName { get; set; }
        public string AccountUserName { get; set; }
        public string AccountPassword { get; set; }
        public Nullable<int> Language { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateOfLastLogin { get; set; }
        public Nullable<int> TimeOffset { get; set; }
        public string Logo { get; set; }
        public string Notes { get; set; }
        public Nullable<int> quietdays { get; set; }
        public Nullable<bool> DSTEnabled { get; set; }
        public Nullable<int> LeakDetectionMode { get; set; }
        public Nullable<double> CentreLongitude { get; set; }
        public Nullable<double> CentreLatitude { get; set; }
        public Nullable<int> QuietMins { get; set; }
        public Nullable<bool> EnableCustomerSideLeak { get; set; }
        public Nullable<bool> EnableStitching { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountLeakOptions> AccountLeakOptions { get; set; }

        public accounts GetAccount(int accountId)
        {
            hwmdbEntities db = new hwmdbEntities();

            var query = (from dba in db.accounts
                         where dba.ID.Equals(accountId)
                         select dba).FirstOrDefault();

            return (accounts)query;
        }

        public List<accounts> GetAccounts(int userId)
        {
            List<accounts> accountsList = new List<accounts>();
            List<int> idAccountList = GetIdAccountList(userId);

            try
            {
                foreach (var item in idAccountList)
                {
                    accountsList.Add(GetAccount(item));
                }
                return accountsList;
            }
            catch
            {
                return null;
            }
        }

        public List<int> GetIdAccountList(int userId)
        {
            hwmdbEntities db = new hwmdbEntities();
            List<int> idAccounts = new List<int>();

            try
            {
                users u = new users();
                int uParent = u.GetUser(userId).ParentAccount;

                var query = (from dba in db.accounts
                             where dba.Parent == uParent
                             select new
                             {
                                 dba.ID
                             }).ToList();

                foreach (var item in query)
                {
                    idAccounts.Add(item.ID);
                }

                return idAccounts;
            }
            catch
            {
                return null;
            }

        }
    }
}
