//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hercules.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alarmconditions
    {
        public int ID { get; set; }
        public Nullable<int> SiteID { get; set; }
        public Nullable<int> channel { get; set; }
        public Nullable<int> AlarmType { get; set; }
        public Nullable<double> HighAlarmLevel { get; set; }
        public Nullable<double> LowAlarmLevel { get; set; }
        public Nullable<int> PersistenceX { get; set; }
        public Nullable<int> PersistenceY { get; set; }
    }
}
