//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hercules.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APIQuotas
    {
        public int ID { get; set; }
        public int AccountID { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> LastAPIRequestDate { get; set; }
        public Nullable<int> RequestsToday { get; set; }
        public Nullable<int> DailyQuota { get; set; }
    }
}
