//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hercules.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationConfigLog
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string PcName { get; set; }
        public string SoftwareName { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
