//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hercules.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationSettings
    {
        public int ID { get; set; }
        public string AppID { get; set; }
        public string SettingName { get; set; }
        public string SettingValue { get; set; }
        public Nullable<System.DateTime> lastupdated { get; set; }
    }
}
