//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hercules.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class audit
    {
        public int id { get; set; }
        public string system { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public Nullable<int> userid { get; set; }
        public string username { get; set; }
        public Nullable<int> siteid { get; set; }
        public string actionnotes { get; set; }
    }
}
