//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hercules.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorrelationResults
    {
        public int Id { get; set; }
        public int RecID1 { get; set; }
        public int RecID2 { get; set; }
        public Nullable<double> Confidence { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<double> LengthUsed { get; set; }
        public Nullable<double> VelocityUsed { get; set; }
        public Nullable<int> MaterialId { get; set; }
    
        public virtual loggerrecordings loggerrecordings { get; set; }
        public virtual loggerrecordings loggerrecordings1 { get; set; }
    }
}
