//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hercules.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dataexport
    {
        public int ID { get; set; }
        public string SiteID { get; set; }
        public string SiteAddress { get; set; }
        public Nullable<System.DateTime> DataTime { get; set; }
        public Nullable<int> ChannelNumber { get; set; }
        public string ChannelName { get; set; }
        public Nullable<double> DataValue { get; set; }
        public Nullable<int> LastDataId { get; set; }
        public Nullable<int> SignalLevel { get; set; }
        public Nullable<int> BatteryLevel { get; set; }
        public Nullable<System.DateTime> LastCallIn { get; set; }
    }
}
