//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hercules.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class exportindex
    {
        public int ID { get; set; }
        public string AppID { get; set; }
        public Nullable<int> SiteID { get; set; }
        public Nullable<int> ChannelNumber { get; set; }
        public Nullable<System.DateTime> DataTime1 { get; set; }
        public Nullable<System.DateTime> DataTime2 { get; set; }
    }
}
