//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hercules.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class firmwareupdates
    {
        public int ID { get; set; }
        public Nullable<int> LoggerID { get; set; }
        public string RequiredVersion { get; set; }
        public Nullable<System.DateTime> DateUpdateStarted { get; set; }
        public Nullable<System.DateTime> DateOfLastCommand { get; set; }
        public Nullable<int> NumTries { get; set; }
        public Nullable<int> status { get; set; }
    }
}
