//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hercules.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fleetreportoptions
    {
        public int ID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<bool> location { get; set; }
        public Nullable<bool> callinreport { get; set; }
        public Nullable<int> callindays { get; set; }
        public Nullable<bool> callinsettings { get; set; }
        public Nullable<bool> rst { get; set; }
        public Nullable<bool> meterreads { get; set; }
        public Nullable<bool> channelsettings { get; set; }
        public Nullable<bool> parameterreport { get; set; }
        public Nullable<bool> pressureflatlines { get; set; }
        public Nullable<bool> overpressures { get; set; }
        public Nullable<bool> negativepressures { get; set; }
        public Nullable<bool> flowflatlines { get; set; }
        public Nullable<bool> zeroflows { get; set; }
        public Nullable<bool> negativeflows { get; set; }
        public Nullable<bool> alarmsettings { get; set; }
        public Nullable<int> parameterreporthours { get; set; }
        public Nullable<bool> includetoday { get; set; }
        public Nullable<bool> batteryReplacemnet { get; set; }
        public Nullable<bool> batteryReplacemnetnext { get; set; }
        public Nullable<bool> pipesize { get; set; }
        public Nullable<bool> pipematerial { get; set; }
        public Nullable<bool> valvelidmodified { get; set; }
        public Nullable<bool> MaintainceNotes { get; set; }
        public Nullable<bool> sensorserialnumber { get; set; }
        public Nullable<bool> warrantyexpire { get; set; }
        public Nullable<bool> servicedate { get; set; }
        public Nullable<bool> equipmentservicecost { get; set; }
        public Nullable<bool> externalbattery { get; set; }
    }
}
