//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hercules.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gascalorificvalues
    {
        public int Id { get; set; }
        public System.DateTime applicable_at { get; set; }
        public System.DateTime applicable_for { get; set; }
        public string ldz { get; set; }
        public double calorificvalue { get; set; }
        public string quality_indicator { get; set; }
        public string substituted { get; set; }
        public System.DateTime created_date { get; set; }
        public System.DateTime generated_timestamp { get; set; }
    }
}
