//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hercules.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hwmdbEntities : DbContext
    {
        public hwmdbEntities()
            : base("name=hwmdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AbortCodeLookup> AbortCodeLookup { get; set; }
        public virtual DbSet<AccountLeakOptions> AccountLeakOptions { get; set; }
        public virtual DbSet<accounts> accounts { get; set; }
        public virtual DbSet<alarmconditions> alarmconditions { get; set; }
        public virtual DbSet<alarmforwarding> alarmforwarding { get; set; }
        public virtual DbSet<alarms> alarms { get; set; }
        public virtual DbSet<alarmTypes> alarmTypes { get; set; }
        public virtual DbSet<APIQuotas> APIQuotas { get; set; }
        public virtual DbSet<ApplicationConfigLog> ApplicationConfigLog { get; set; }
        public virtual DbSet<ApplicationSettings> ApplicationSettings { get; set; }
        public virtual DbSet<associations> associations { get; set; }
        public virtual DbSet<audit> audit { get; set; }
        public virtual DbSet<BandPassFilter> BandPassFilter { get; set; }
        public virtual DbSet<CategoryofPermitCodeLookup> CategoryofPermitCodeLookup { get; set; }
        public virtual DbSet<celltable> celltable { get; set; }
        public virtual DbSet<channels> channels { get; set; }
        public virtual DbSet<CorrelationResults> CorrelationResults { get; set; }
        public virtual DbSet<dataexport> dataexport { get; set; }
        public virtual DbSet<datapoints> datapoints { get; set; }
        public virtual DbSet<exportindex> exportindex { get; set; }
        public virtual DbSet<FavouriteSignalList> FavouriteSignalList { get; set; }
        public virtual DbSet<FavouriteSignalListData> FavouriteSignalListData { get; set; }
        public virtual DbSet<firmwareupdates> firmwareupdates { get; set; }
        public virtual DbSet<fleetreportoptions> fleetreportoptions { get; set; }
        public virtual DbSet<flowpegasus> flowpegasus { get; set; }
        public virtual DbSet<gascalorificvalues> gascalorificvalues { get; set; }
        public virtual DbSet<gaszone> gaszone { get; set; }
        public virtual DbSet<InstallationReport> InstallationReport { get; set; }
        public virtual DbSet<installsite> installsite { get; set; }
        public virtual DbSet<leakconfirmation> leakconfirmation { get; set; }
        public virtual DbSet<leakconfirmationassociation> leakconfirmationassociation { get; set; }
        public virtual DbSet<LeakDetectionOptions> LeakDetectionOptions { get; set; }
        public virtual DbSet<leakstatuslookup> leakstatuslookup { get; set; }
        public virtual DbSet<loggerconfigurationdata> loggerconfigurationdata { get; set; }
        public virtual DbSet<loggermeterreadings> loggermeterreadings { get; set; }
        public virtual DbSet<loggerrecordings> loggerrecordings { get; set; }
        public virtual DbSet<loggers> loggers { get; set; }
        public virtual DbSet<lookuptables> lookuptables { get; set; }
        public virtual DbSet<Maintenance> Maintenance { get; set; }
        public virtual DbSet<messageindex> messageindex { get; set; }
        public virtual DbSet<messages> messages { get; set; }
        public virtual DbSet<networklookup> networklookup { get; set; }
        public virtual DbSet<openchannelconversion> openchannelconversion { get; set; }
        public virtual DbSet<openchannelheader> openchannelheader { get; set; }
        public virtual DbSet<PipeNetwork> PipeNetwork { get; set; }
        public virtual DbSet<pmzbigtimedata> pmzbigtimedata { get; set; }
        public virtual DbSet<pmzoffstimedata> pmzoffstimedata { get; set; }
        public virtual DbSet<pmzpressflowdata> pmzpressflowdata { get; set; }
        public virtual DbSet<pmzpresstimedata> pmzpresstimedata { get; set; }
        public virtual DbSet<pmzsettings> pmzsettings { get; set; }
        public virtual DbSet<recentsites> recentsites { get; set; }
        public virtual DbSet<recordingspoints> recordingspoints { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<sitephotos> sitephotos { get; set; }
        public virtual DbSet<sites> sites { get; set; }
        public virtual DbSet<smsjobtable> smsjobtable { get; set; }
        public virtual DbSet<smsrequesttable> smsrequesttable { get; set; }
        public virtual DbSet<softwarelookup> softwarelookup { get; set; }
        public virtual DbSet<SoundVelocityLookup> SoundVelocityLookup { get; set; }
        public virtual DbSet<statuspegasus> statuspegasus { get; set; }
        public virtual DbSet<steptestcredits> steptestcredits { get; set; }
        public virtual DbSet<steptesthistory> steptesthistory { get; set; }
        public virtual DbSet<SystemNotification> SystemNotification { get; set; }
        public virtual DbSet<timepegasus> timepegasus { get; set; }
        public virtual DbSet<TMAOptions> TMAOptions { get; set; }
        public virtual DbSet<torancounts> torancounts { get; set; }
        public virtual DbSet<unitslookup> unitslookup { get; set; }
        public virtual DbSet<UserNotificationAcknowledgement> UserNotificationAcknowledgement { get; set; }
        public virtual DbSet<userpasswords> userpasswords { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<witsendpoints> witsendpoints { get; set; }
        public virtual DbSet<witssitedetails> witssitedetails { get; set; }
        public virtual DbSet<ChamberTypes> ChamberTypes { get; set; }
        public virtual DbSet<histograms> histograms { get; set; }
        public virtual DbSet<hubs> hubs { get; set; }
        public virtual DbSet<PipeDiameterRanges> PipeDiameterRanges { get; set; }
        public virtual DbSet<PipeMaterialTypes> PipeMaterialTypes { get; set; }
        public virtual DbSet<PipeSize> PipeSize { get; set; }
        public virtual DbSet<RTLTransmitters> RTLTransmitters { get; set; }
    }
}
