//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hercules.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstallationReport
    {
        public int Id { get; set; }
        public string ReportStatus { get; set; }
        public Nullable<int> AbortCode { get; set; }
        public string SiteId { get; set; }
        public string Region { get; set; }
        public string Area { get; set; }
        public string SiteName { get; set; }
        public string SMPArea { get; set; }
        public string NodeRef { get; set; }
        public string FLOC { get; set; }
        public string InstallationType { get; set; }
        public string MonitorType { get; set; }
        public string LoggerSerialNumber { get; set; }
        public string LoggerSmsNo { get; set; }
        public Nullable<int> LoggingRate { get; set; }
        public string SensorType { get; set; }
        public string SensorSerialNumbers { get; set; }
        public string SiteVisitFrequency { get; set; }
        public string SiteLocation { get; set; }
        public Nullable<bool> Infrastructure { get; set; }
        public Nullable<bool> SiteAccessRequired { get; set; }
        public string AssetCondition { get; set; }
        public string AerialPosition { get; set; }
        public string AerialUsed { get; set; }
        public Nullable<double> SignalStrength { get; set; }
        public Nullable<double> SignalStrengthAboveGround { get; set; }
        public Nullable<bool> GPRSTestPassed { get; set; }
        public Nullable<bool> CanMarkerBePromoted { get; set; }
        public Nullable<double> Depth { get; set; }
        public Nullable<double> Velocity { get; set; }
        public Nullable<double> PipeSize { get; set; }
        public string PipeShape { get; set; }
        public string LoggerLocation { get; set; }
        public Nullable<double> SpillLevel { get; set; }
        public Nullable<int> ChamberCategory { get; set; }
        public string ChamberLidWeight { get; set; }
        public string ChamberLocation { get; set; }
        public Nullable<double> ChamberDepth { get; set; }
        public string MechanizedScreen { get; set; }
        public Nullable<bool> Pumps { get; set; }
        public Nullable<bool> TelemetryPresent { get; set; }
        public Nullable<bool> VirtualRiskAssessmentCompleted { get; set; }
        public Nullable<bool> TrafficManagementReq { get; set; }
        public Nullable<bool> PermitRequired { get; set; }
        public Nullable<bool> ConfinedSpaceNC { get; set; }
        public Nullable<bool> AreKeysRequired { get; set; }
        public string SiteContactDetails { get; set; }
        public Nullable<bool> OutOfHoursInstallation { get; set; }
        public Nullable<bool> CommercialPremises { get; set; }
        public string SiteSpecificRequirements { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> DateSubmitted { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<bool> IsThereEquipmentInChamber { get; set; }
        public Nullable<double> DepthOffset { get; set; }
        public Nullable<bool> NoticeRequired { get; set; }
        public Nullable<int> CategoryPermit { get; set; }
        public Nullable<bool> PermitClosed { get; set; }
        public string LatEast { get; set; }
        public string LongNorth { get; set; }
        public string HeightAOD { get; set; }
        public string RemovedMonitorSerialNumber { get; set; }
        public Nullable<bool> HasHealthandSafety { get; set; }
        public string HasHealthandSafetyComments { get; set; }
        public string BatterySerialNumber { get; set; }
        public Nullable<double> Flow { get; set; }
        public string RemovedMonitorType { get; set; }
        public Nullable<System.DateTime> DateSignedOff { get; set; }
        public Nullable<bool> SonicSens { get; set; }
        public Nullable<bool> VelocitySens { get; set; }
        public Nullable<bool> DepthSens { get; set; }
        public Nullable<bool> FloodAlarmSens { get; set; }
        public Nullable<bool> DopplerSens { get; set; }
        public Nullable<double> SpillLevel90 { get; set; }
        public string SpillAlarmTime { get; set; }
        public Nullable<bool> ComplexTM { get; set; }
        public string TypeofAbort { get; set; }
        public string InstallationCategory { get; set; }
        public Nullable<double> SensorHeight { get; set; }
        public string RecommendationsForSignalImpr { get; set; }
    }
}
