//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hercules.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loggerconfigurationdata
    {
        public int ID { get; set; }
        public int LoggerID { get; set; }
        public int Address { get; set; }
        public byte[] data { get; set; }
        public byte[] validflags { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
    }
}
