//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hercules.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loggerrecordings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public loggerrecordings()
        {
            this.CorrelationResults = new HashSet<CorrelationResults>();
            this.CorrelationResults1 = new HashSet<CorrelationResults>();
        }
    
        public int ID { get; set; }
        public Nullable<int> LoggerID { get; set; }
        public string SiteID { get; set; }
        public Nullable<System.DateTime> RST { get; set; }
        public Nullable<System.DateTime> RET { get; set; }
        public Nullable<int> RecordingType { get; set; }
        public Nullable<int> Site_ID { get; set; }
        public Nullable<int> sampleratems { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CorrelationResults> CorrelationResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CorrelationResults> CorrelationResults1 { get; set; }
    }
}
