//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hercules.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loggers
    {
        public int ID { get; set; }
        public string LoggerType { get; set; }
        public string LoggerSoftware { get; set; }
        public string LoggerSerialNumber { get; set; }
        public string LoggerSMSNumber { get; set; }
        public string LoggerGSMNumber { get; set; }
        public Nullable<int> OwnerAccount { get; set; }
        public Nullable<System.DateTime> LastCallIn { get; set; }
        public Nullable<System.DateTime> RST { get; set; }
        public Nullable<int> SignalLevel { get; set; }
        public Nullable<double> BatteryLevel { get; set; }
        public Nullable<int> LogRateMs { get; set; }
        public Nullable<int> NetID { get; set; }
        public Nullable<int> LAC { get; set; }
        public Nullable<int> CellID { get; set; }
        public Nullable<double> MastLongitude { get; set; }
        public Nullable<double> MastLatitude { get; set; }
        public Nullable<long> DataCount { get; set; }
        public string Notes { get; set; }
        public string LastMessageType { get; set; }
        public Nullable<int> CallFrequency { get; set; }
        public Nullable<bool> IsRoaming { get; set; }
        public Nullable<int> MonthlyDownloadLimit { get; set; }
        public Nullable<int> SMSCredits { get; set; }
        public string LoggerNetwork { get; set; }
        public Nullable<System.DateTime> RTC { get; set; }
        public Nullable<int> TA { get; set; }
        public Nullable<int> LastCallStatus { get; set; }
        public Nullable<int> Watchdogs { get; set; }
        public Nullable<System.DateTime> ServiceDate { get; set; }
        public Nullable<System.DateTime> WarrantyExpiry { get; set; }
        public string ServiceDescription { get; set; }
        public Nullable<decimal> EquipmentServiceCost { get; set; }
        public Nullable<System.DateTime> BatteryReplacement { get; set; }
        public Nullable<System.DateTime> BatteryReplacementNext { get; set; }
        public Nullable<byte> UTCOffset { get; set; }
        public Nullable<bool> ExternalBattery { get; set; }
        public Nullable<double> FlightTimeSecs { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> NetRegistrationTime { get; set; }
    }
}
