//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hercules.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenance
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> InstallationReportId { get; set; }
        public string Reason { get; set; }
        public string TypeofMaintenance { get; set; }
        public Nullable<System.DateTime> DateRequested { get; set; }
        public string Status { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public Nullable<System.DateTime> DateToBeCompleted { get; set; }
        public string AddiontionInfo { get; set; }
        public Nullable<int> AbortCode { get; set; }
        public string PerformedMaintenance { get; set; }
        public string DescriptionOfLocation { get; set; }
        public string MonitorSN { get; set; }
        public string FinalSignalStrength { get; set; }
        public string MainReason { get; set; }
        public string SecondaryReason { get; set; }
        public Nullable<double> Depth { get; set; }
        public Nullable<double> PipeSize { get; set; }
        public Nullable<double> DepthOffset { get; set; }
        public string PipeShape { get; set; }
        public Nullable<double> Velocity { get; set; }
        public Nullable<double> SpillLevel { get; set; }
        public Nullable<double> Flow { get; set; }
        public Nullable<bool> hasHealthAndSafety { get; set; }
        public Nullable<int> CompletedBy { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public string CompletionComments { get; set; }
        public string PONumber { get; set; }
        public Nullable<System.DateTime> DateSignedOff { get; set; }
        public string DeclinedComments { get; set; }
        public Nullable<System.DateTime> DateDeclined { get; set; }
        public Nullable<int> RelocationInstallationID { get; set; }
        public Nullable<bool> ComplexTM { get; set; }
        public Nullable<bool> TMARequired { get; set; }
        public string SonicSensNumber { get; set; }
        public string AerialUsed { get; set; }
        public Nullable<System.DateTime> DateAssigned { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<int> maintenanceRequestID { get; set; }
        public string MonitorSMSNumber { get; set; }
        public Nullable<int> ComplexTMAID { get; set; }
    }
}
