//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hercules.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class messages
    {
        public long ID { get; set; }
        public Nullable<byte> flags { get; set; }
        public string siteid { get; set; }
        public string smsnumber { get; set; }
        public Nullable<byte> battery { get; set; }
        public Nullable<byte> csq { get; set; }
        public byte[] data { get; set; }
        public Nullable<System.DateTime> rxtime { get; set; }
    }
}
