//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hercules.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pmzpressflowdata
    {
        public int ID { get; set; }
        public Nullable<int> PmzId { get; set; }
        public Nullable<double> Flow { get; set; }
        public Nullable<double> Pressure { get; set; }
        public Nullable<int> DayType { get; set; }
    }
}
