//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hercules.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pmzsettings
    {
        public int ID { get; set; }
        public Nullable<short> ControlMode { get; set; }
        public Nullable<double> CPMin { get; set; }
        public Nullable<double> CPTarget { get; set; }
        public Nullable<double> AlarmOffset { get; set; }
        public Nullable<int> ControlInterval { get; set; }
        public Nullable<double> DeadBand { get; set; }
        public Nullable<double> CPBand { get; set; }
        public Nullable<int> CPRetryCount { get; set; }
        public Nullable<int> FlowAverage { get; set; }
        public Nullable<int> NightStartMins { get; set; }
        public Nullable<int> NightEndMins { get; set; }
        public Nullable<double> NightOffset { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> SitePrvId { get; set; }
        public Nullable<int> SiteCpId { get; set; }
        public Nullable<int> SiteCp2Id { get; set; }
        public Nullable<int> SiteCp3Id { get; set; }
        public Nullable<short> LatchMode { get; set; }
        public Nullable<short> CpChan { get; set; }
        public Nullable<short> Cp2Chan { get; set; }
        public Nullable<short> Cp3Chan { get; set; }
        public Nullable<int> TableUpdateFreq { get; set; }
        public Nullable<System.DateTime> NextUpdateTime { get; set; }
        public Nullable<System.DateTime> LastPRVRestart { get; set; }
        public Nullable<double> FaultPressure { get; set; }
        public Nullable<int> FaultTimeout { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<short> UpdateType { get; set; }
        public Nullable<double> DeadBandLimit { get; set; }
        public Nullable<double> ActuatorMax { get; set; }
        public Nullable<double> ActuatorMin { get; set; }
        public Nullable<short> ControlFlags { get; set; }
        public Nullable<double> MaxValidFlow { get; set; }
        public Nullable<double> MinValidFlow { get; set; }
        public Nullable<System.DateTime> SummerStart { get; set; }
        public Nullable<System.DateTime> SummerEnd { get; set; }
        public Nullable<int> SummerOffset { get; set; }
        public string SerialNumberPrv { get; set; }
        public string SerialNumberCp { get; set; }
        public Nullable<double> MaxInletPres { get; set; }
        public Nullable<double> MinInletPres { get; set; }
        public Nullable<double> MaxOutletPres { get; set; }
        public Nullable<double> MinOutletPres { get; set; }
        public Nullable<double> MaxTopPres { get; set; }
        public Nullable<double> MinTopPres { get; set; }
        public Nullable<double> MaxFlow { get; set; }
        public Nullable<double> MinFlow { get; set; }
        public Nullable<System.DateTime> SolenoidDate { get; set; }
        public Nullable<int> SolenoidCount { get; set; }
        public Nullable<bool> BigTimeTable { get; set; }
        public Nullable<byte> BigTimeDays { get; set; }
        public Nullable<double> MaxValidCp { get; set; }
        public Nullable<double> MinValidCp { get; set; }
        public Nullable<short> CpMode { get; set; }
        public Nullable<int> CPNightStartMins { get; set; }
        public Nullable<int> CPNightEndMins { get; set; }
        public Nullable<System.DateTime> HolStart { get; set; }
        public Nullable<System.DateTime> HolEnd { get; set; }
        public Nullable<bool> HolOn { get; set; }
        public Nullable<int> MasterPmzId { get; set; }
        public Nullable<int> MasterPmzOffs { get; set; }
        public Nullable<short> LastControlMode { get; set; }
        public Nullable<System.DateTime> LastCheckTime { get; set; }
        public bool LearningModeComplete { get; set; }
        public Nullable<double> SolenoidActuationThreshold { get; set; }
        public Nullable<byte> BigTimeHols { get; set; }
        public string LearningStatus { get; set; }
        public Nullable<int> LearningDataLimit { get; set; }
    }
}
