//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hercules.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sitephotos
    {
        public int Id { get; set; }
        public Nullable<int> SiteId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> InstallReportID { get; set; }
        public Nullable<int> CompletionReportID { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<int> MaintenanceID { get; set; }
    }
}
