//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hercules.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class torancounts
    {
        public int ID { get; set; }
        public string ToranName { get; set; }
        public Nullable<System.DateTime> DataTime { get; set; }
        public Nullable<int> MessageCount { get; set; }
    }
}
