//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hercules.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userpasswords
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string PasswordHash { get; set; }
    
        public virtual users users { get; set; }
    }
}
