//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hercules.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class witssitedetails
    {
        public int ID { get; set; }
        public Nullable<int> SiteID { get; set; }
        public Nullable<int> dnp3id { get; set; }
        public string Witstring0 { get; set; }
        public string Witstring1 { get; set; }
        public string Witstring2 { get; set; }
        public string Witstring3 { get; set; }
        public string Witstring4 { get; set; }
        public string Witstring5 { get; set; }
        public string Witstring6 { get; set; }
        public string Witstring7 { get; set; }
    }
}
