//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hercules.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class witsendpoints
    {
        public int ID { get; set; }
        public Nullable<bool> enabled { get; set; }
        public Nullable<int> accountID { get; set; }
        public string serveraddress { get; set; }
        public Nullable<int> serverport { get; set; }
        public Nullable<int> serverdnp3address { get; set; }
        public Nullable<int> serverconnecttimeout { get; set; }
        public Nullable<int> servercommstimeout { get; set; }
        public Nullable<long> lastmessageid { get; set; }
        public Nullable<System.DateTime> lastexportdate { get; set; }
        public Nullable<int> lastexportedsiteid { get; set; }
        public Nullable<int> status { get; set; }
    }
}
